# Generated by Django 4.2 on 2023-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('test', models.CharField(max_length=100)),
                ('B2B_price', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('cancel', 'cancel')], default='pending', max_length=50)),
                ('B2C_price', models.IntegerField()),
                ('B2C_Status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('cancel', 'cancel')], default='pending', max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
