# Generated by Django 4.2 on 2023-04-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_patient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
    ]
